#!/bin/bash

set -o nounset -o pipefail -o errexit

ACTION=
FORCE=
while getopts "cmzZidufc-" OPT; do
    case $OPT in
        c) ACTION=compile ;;
        m) ACTION=latexmk ;;
        z) ACTION=clean ;;
        Z) ACTION=deepclean ;;
        i) ACTION=install ;;
        d) ACTION=deps ;;
        u) ACTION=update ;;
        e) # shellcheck disable=SC2209
           ACTION=exec ;;
        f) FORCE=1 ;;
        -) break ;;
        ?) exit 2 ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$ACTION" ]; then
    echo 1>&2 "specify an action"
    exit 1
fi

if [ "$ACTION" = "install" ]; then
    if [ -n "$FORCE" ]; then
        export TEXHELP_FORCE=1
    fi

    TMP=$(mktemp -d)
    trap 'rm -rf $TMP' EXIT
    git clone --depth=1 "https://github.com/rootmos/texhelp" "$TMP"
    "$TMP/install.sh"
fi

resolve() {
    local dir
    dir=$PWD
    while true; do
        if [ -e "$dir/$1" ]; then
            echo "$dir/$1"
            return 0
        fi

        if [ -e "$dir/.git" ]; then
            break
        fi

        dir=$(readlink -f "$dir/..")
    done
    echo 1>&2 "unable to recursively resolve: $1"
    return 1
}

if [ -z "${TEXHELP_ROOT-}" ]; then
    ROOT=$(resolve ".texhelp")
    # shellcheck source=/dev/null
    . "$ROOT/activate"
fi

if [ "$ACTION" = "compile" ]; then
    pdflatex --halt-on-error --interaction=nonstopmode "$@"
elif [ "$ACTION" = "latexmk" ]; then
    latexmk -interaction=nonstopmode -pdf "$@"
elif [ "$ACTION" = "clean" ] || [ "$ACTION" = "deepclean" ]; then
    rm -vf *.aux *.bbl *.bcf *.blg *.fls *.run.xml *.fdb_latexmk *.log *.out *.pdf *.dvi *-SAVE-ERROR
    if [ "$ACTION" = "deepclean" ]; then
        rm -rf "$ROOT"
        echo 1>&2 "removed: '$ROOT'"
    fi
elif [ "$ACTION" = "deps" ] || [ "$ACTION" = "install" ]; then
    DEPS=$(resolve "tl.deps" || true)
    if [ -n "${DEPS-}" ]; then
        echo 1>&2 "TeX Live dependencies spec: $DEPS"
        sed 's/#.*//' "$DEPS" | sed '/^$/d' | xargs tlmgr install
    fi
elif [ "$ACTION" = "update" ]; then
    tlmgr update --all
elif [ "$ACTION" = "exec" ]; then
    "$@"
fi
