name: Tests
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 7 * *"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        distro: [ "alpine", "ubuntu", "archlinux" ]
    runs-on: ubuntu-latest
    container:
        image: ${{ matrix.distro }}:latest
    env:
      DEPS_DISTRO: ${{ matrix.distro }}
    steps:
    - name: Check out preparation files
      uses: actions/checkout@v6
      with:
        sparse-checkout: .github/prepare
        sparse-checkout-cone-mode: false

    - name: Prepare environment
      run: .github/prepare -u

    - name: Check out repository code
      uses: actions/checkout@v6

    - name: Install build dependencies
      run: .github/deps -b

    - name: Run installer
      run: ./install.sh

    - name: Try activating the environment
      run: |
        set -o nounset -o errexit
        . .texhelp/activate
        latex --version

    - name: Run tlmgr update
      run: |
        . .texhelp/activate
        tlmgr update --all

    - name: Install test dependencies
      run: .github/deps -t

    - name: Run test
      run: .github/test.sh
